### PR TITLE
add new output for maximum/minimum over time of tied contact forces and pressures /H3D/NODA/CONT2/TMAX , /H3D/NODA/CONT2/TMIN , /H3D/NODA/PCONT2/TMAX and /H3D/NODA/PCONT2/TMIN

### PR DESCRIPTION
**Pull request by MahaHachani**
#### Checklist

- [x] The title of the PR is reviewed
- [x] There is no text before the checklist section
- [x] The following two sections are filled (or deleted)
- [x] This PR has been previewed 

#### Description of the feature or the bug

/H3D/NODA/CONT2 maximum and minimum contact force
/H3D/NODA/PCONT2 maximum and minimum contact pressure

### CODE REVIEW

**Comment by laurent-altr** [comment]
I reviewed the title. Also, I am not sure about the naming: why PCONT2?

**Comment by MahaHachani** [comment]
Hi Laurent, 
It is not  the right title that you changed.
I changed it now
Cont2 and Pcont2 because it is for tied contact inter2 but it is not the forces that we output it is the maximum/minimum over time

**Comment by laurent-altr** [comment]
I'll let @sebastienVilleneuve review this PR because I am not sure to follow: the option names in the title and the body are differents.

**Comment by MahaHachani** [comment]
Ok but I don't the difference

**Comment by laurent-altr** [comment]
The names in the title in red, are different from the names in the description in green. Which ones are correct?
image

**Review by sebastienVilleneuve — CHANGES_REQUESTED** [review]
Hi @MahaHachani 

I let you make changes to have one function/subroutine per file.

Thanks,
Sébastien

**Comment by MahaHachani** [comment]
> Hi @MahaHachani
> 
> I let you make changes to have one function/subroutine per file.
> 
> Thanks, Sébastien

Done Sebastien

**Pull request merged**
