### PR TITLE
Fix remaining typos in `hm_cfg_files/`

### PR DESCRIPTION
**Pull request by luzpaz**
#### Description of the feature or the bug
Typo fixes.  
Follow-up to #526

#### Description of the changes
self-explanatory

### CODE REVIEW

**Comment by sebastienVilleneuve** [comment]
Hi Luzpaz,

Thanks so much for the contribution,
Before merging we need to make some additional checks since the typo you modified are not only comments.

Thanks,
Sébastien

**Comment by luzpaz** [comment]
Looks llke some unicode was unintentionally altered by vscode. I need to fix that before merge. Switching to Draft

**Comment by luzpaz** [comment]
Reverted unicode changes that vscode automatically implemented in [5814b19](https://github.com/OpenRadioss/OpenRadioss/pull/530/commits/5814b19e80ed2f34e0be2a7f583ac78464c65bd9)

**Comment by luzpaz** [comment]
Rebased on latest `main` branch

**Comment by luzpaz** [comment]
Resubmitted reverted changed but edited them differently this time. See [5a5ccc8](https://github.com/OpenRadioss/OpenRadioss/pull/530/commits/5a5ccc8b98de1b8452e6dcda7a333239b2e063a8)

**Comment by luzpaz** [comment]
Please review at your convenience

**Comment by luzpaz** [comment]
bump

**Comment by sebastienVilleneuve** [comment]
Hi @luzpaz 
thanks for the contributions .
Before merging your corrections we need to make precise checks .

We need also to check that some of your numerous changes does not break some reading.

Regards,
Sébastien

**Comment by luzpaz** [comment]
I'll break this PR down further so it's more manageable to review

**Comment by luzpaz** [comment]
Closing in favor of #710

**Pull request closed without merging**
