### PR TITLE
allows part selection for /H3D/NODA/GPS/TMAX to save computation times

### PR DESCRIPTION
**Pull request by qiangRadioss**
#### Checklist

- [x] The title of the PR is reviewed
- [x] There is no text before the checklist section
- [x] The following two sections are filled (or deleted)
- [x] This PR has been previewed 

#### Description of the feature or the bug

TMAX (max value over times) compute takes a lot of times, especially for GPS output

#### Description of the changes

adding part selection for these high computation time option like /H3D/NODA/GPS/TMAX to improve the performance.

### CODE REVIEW

**Comment by laurent-altr** [comment]
I marked this PR as a draft. We may need to discuss with @OlivierWienholtz about the performance issue.
In particular, `TENSGPS3` is working at the group level, but it is called outside of the element part. Redoing the gather/scatter at each cycle may be the main reason of the performance issue.

**Comment by qiangRadioss** [comment]
Hi Laurant,
with /MON/FULL, it has been shown that the high computation is not come from TENSGPS3 but SIG3DPIN2H which calculates eigenvalues of (3,3) over numnod.
By removing the calling of this subroutine or calling it per 10 cycle, the over cost issue could be fixed.
Could you help me to look at if we can improve the performance of this subroutine?
(otherwise we have at least the solution of the calling by 10 cycle)

thanks

**Comment by laurent-altr** [comment]
Hi @qiangRadioss, 

Is this computation necessary or could you simply remove it as you proposed?
Also note that SIG3DPIN2H may not work as expected on some compilers because of the `INTENT(OUT)`.

**Comment by qiangRadioss** [comment]
after some discussions, new input /H3D/GPS/TMAX/N=i (i=number of cycle) has been added as well(also for GPSTRAIN), now GPS/TMAX isn't computed at each cycle , but each i cycles.
(ref : RD-14201 to see detail discussions)

**Comment by qiangRadioss** [comment]
done, let me know if everthing is ok?
thanks.
Qiang.

**Comment by qiangRadioss** [comment]
strange, i've done "git rebase -i main" and squash each time.
something wrong.
i'm looking it.
thanks.
Qiang.

**Review by sebastienVilleneuve — APPROVED** [review]

**Pull request merged**
